apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf
          imagePullPolicy: Never
          volumeMounts:
            - name: telegraf
              mountPath: /var/run/docker.sock
      volumes:
        - name: telegraf
          hostPath:
            path: /var/run/docker.sock